name: Docker dev

on:
  push:
    branches: [ "dev" ]


jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
        
      - name: Build the Docker image at ${{github.GITHUB_REPOSITORY }}
        run: docker build . --file Dockerfile --tag registry.jlosch.de/jlosch.de/website:dev

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          name: registry.jlosch.de/jlosch.de/website:dev
